
language: R

cache: packages

sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8

warnings_are_errors: false

r_packages:
  - data.table
  - udunits2
  - units
  - sf
  - plotrix
  - leaflet

notifications:
  email:
    on_success: change
    on_failure: change

