
# see https://docs.travis-ci.com/user/languages/r/

language: r
r:
  - oldrel
  - release
  - devel

cache: packages

sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

dist: trusty

warnings_are_errors: false

r_packages:
  - data.table
  - udunits2
  - units
  - sf
  - plotrix
  - leaflet

r_github_packages:
  - virgesmith/humanleague

notifications:
  email:
    on_success: change
    on_failure: change

