
language: R

cache: packages

sudo: false

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode8

warnings_are_errors: false

r_packages:
  - data.table
  - udunits2
  - units
  - sf
  - plotrix
  - leaflet

notifications:
  email:
    on_success: change
    on_failure: change

